# syntax=docker/dockerfile:1

FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_LOGO_PATH
ARG NEXT_PUBLIC_MODEL_3D_PATH
ARG NEXT_PUBLIC_CONTACT_PHONE
ARG NEXT_PUBLIC_CONTACT_PHONE_HREF
ARG NEXT_PUBLIC_CONTACT_EMAIL
ARG NEXT_PUBLIC_CONTACT_ADDRESS
ARG NEXT_PUBLIC_CONTACT_WORKING_HOURS
ARG NEXT_PUBLIC_SOCIAL_TELEGRAM
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM
ARG NEXT_PUBLIC_SOCIAL_WHATSAPP
ARG NEXT_PUBLIC_SOCIAL_TIKTOK
ARG NEXT_PUBLIC_SOCIAL_TELEGRAM_LABEL
ARG NEXT_PUBLIC_SOCIAL_INSTAGRAM_LABEL
ARG NEXT_PUBLIC_SOCIAL_WHATSAPP_LABEL
ARG NEXT_PUBLIC_SOCIAL_TIKTOK_LABEL

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
